# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fe1625bc48cf672a2643917c1e84a38a238b04b90b84979a52a254e981651529d64b78c98bffb53f8b3115270fac9c2b875a3b2b93730dc4579e0f5f6314b74

test:
  secret_key_base: 60aa1d3bce881dedb2edf593bfd3d8892f0fb8cd1d77007782b0f0327fb07b777a9b2f5d0fe2905c58644a4316159f5edf0a01359567f0fdd6dd5e34dfa3a72c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
